<?php

$norserunes = array(
	"1" => array("The Self","Mannaz","The starting point should always be the self, and a proper relationship with yourself is essential: on this depends that all other relationships may flow properly, including your relationship with the Great Mystery.\nThis is not a moment to look for praise about your achievements, nor is it the time to put all your attention in possible results. Do not judge and dont be intolerant. Remember the past and think about the future, but focus on the present. Try to live your ordinary life in an extraordinary manner.","runes/01theself.jpg"),
	"2" => array("Partnership","Gebo","Fortune smiles, and nice surprises will arrive unexpectedly. Something positive is on its way, something that is totally deserved. You will probably receive awards, maybe a promotion, an acknowledgement or a gift. There is hope and joy. There are fulfilled promises and dreams come true. There is grace and forgiveness.\nMaybe some type of partnership is about to be born. If this is the case, Gebo reminds you to keep your individuality: remember that true partnership occurs when two beings form a team, each one retaining their own singularity.","runes/02partnership.jpg"),
	"3" => array("Signals","Ansuz","This Rune advises you to expect the unexpected. It is a message that calls you towards change and renovation, maybe even towards a new life. There will be new relations, new links, new contacts created, and therefore it is recommended that you keep your eyes and ears open during meetings or casual encounters.\nOn the other hand, Ansuz reminds you that you must first love and nourish yourself before trying to love and nourish others: it is impossible to give what one does not have. This Rune reminds you to remind yourself.","runes/03signals.jpg"),
	"4" => array("Separation","Othila","This is the Rune of beneficial gain. It indicates a moment in which tangible preparation will yield tangible results. It is an excellent opportunity to learn, to become better, to expand. New acquisitions will be favoured.\nIt also introduces a time of blessings in which actions taken will very probably be successful and bring new and better opportunities for growth. This is a moment that, if recognized, will reward you with all kinds of important benefits for your development.","runes/04separation.jpg"),
	"5" => array("Strength","Uruz","This is the Rune of endings and new beginnings. It is a Rune of transition indicating that the life you have lived until now must change to make room for a new form. You might suffer the loss of something or someone with whom you hold strong emotional links. However, Uruz reminds you that it is an entirely natural process: death, fertilization, gestation and rebirth. The ashes fertilize the ground for future crops.\nLearn to adapt to the moment, using the strength of your masculinity or femininity as support, and look for the opportunity that hides behind the loss.","runes/05strength.jpg"),
	"6" => array("Initiation","Perth","This Rune is associated with the Phoenix, the mystical bird that consumes itself in the fire to later rise from its own ashes. Powerful forces of change and renovation are in movement.\nOn the side of the mundane, there will probably be surprises such as sudden gains or the start of an unexpected relationship. On the spiritual side, it is time to rise above yourself, above ordinary living, in order to acquire a wider vision. Perth reminds you that the external is unimportant, except when it is a reflection of the internal.","runes/06initiation.jpg"),
	"7" => array("Constraint","Nauthiz","Drawing this Rune indicates that there might be delays and changes in the direction of your actions. There are strong reasons to review your plans carefully. Restriction is necessary.\nNauthiz suggests to identify your Shadow, the dark side of your nature whch reflects to the outside in the form of weakness. Try to discover what is it within you that attracts misfortune to your life. Difficulties and failures, however, can teach us plenty about ourselves. If necessary, rectify your direction and restore your internal balance. Look for the positive side of adversity.","runes/07constraint.jpg"),
	"8" => array("Fertility","Inguz","This Rune represents the need to share, to be wanted, the search for similarities and an impulse towards harmony in personal relationships. It could well signal a new way, a new relationship, even a new life.\nInguz symbolizes the end of a time of lethargy, a liberation from tension and uncertainty. However, it is necessary to fertilize the ground for such liberation.\nKeep your feet on the ground and stay away from any undesirable influences. This is a good moment to complete any project pending in your life.","runes/08fertility.jpg"),
	"9" => array("Defense","Eihwaz","This Rune is related to the difficulties that arise at the beginning of a new life and the defenses that we build around us when facing the unknown. It often announces a time of waiting, and thus its main advice is patience. \nIt is recommended to foresee consequences before acting. Once your decision is totally clear, then you will be able to carry out the action with ease. Take advantage of this moment to put your house in order and to tend to your personal affairs.","runes/09defense.jpg"),
	"10" => array("Protection","Algiz","Opportunities and new challenges are characteristic of this Rune. With them, however, unwanted influences may arrive, and thus it becomes necessary to protect yourself. Here, your maximum protection is the right action at the right moment.\nIf you are experiencing pain, dont deny it or try to hide from what is happening. Observe it and learn from it, feel it and let it go: the more you allow yourself to feel it, the faster you will be able to release it. Algiz reminds you that you will grow, and being aware of this may be your best protection in moments of doubt.","runes/10protection.jpg"),
	"11" => array("Possessions","Fehu","This is the Rune of realization: an ambition satisfied, a love conquered, a reward received. It often signals the presence of abundant nourishment of all kinds, physical as well as spiritual.\nNevertheless, it reminds you that in moments of good fortune we run the risk of getting carried away by success, thus behaving imprudently. Fehu advises you to be aware of this so as to not let it happen.\nEnjoy your good fortune and dont forget to share it: the good will of feeding others is a sign of a well-fed being.","runes/11possessions.jpg"),
	"12" => array("Joy","Wunjo","This Rune announces a state of security and relaxation, a sense of well-being. Light is finally peeking through the clouds, fruits hang heavy on the branches, and bad times are finally staying behind.\nYou may see yourself surrounded by joy, pleasure and comfort both at home and outside. There is clarity and a new energy that will allow you to understand, to balance, to renew yourself and your personal relations.\nNecessary changes have already been carried out, and now you may rejoice and receive Wunjos blessings freely.","runes/12joy.jpg"),
	"13" => array("Harvest","Jera","This Rune often announces a fertile season, a happy coming to term. Jera is the Rune of beneficial results relating to any activity or interest that concerns you at this moment of your life. You have prepared the ground and planted the seed, and now you must cultivate it. Jera offers an incentive towards success.\nDont expect fast results, however. As with a harvest, a cultivation cycle or maturing process is needed to finally be able to recollect the fruits of your labour. You have done a good job, and now Jera advises you to persevere and to be patient.","runes/13harvest.jpg"),
	"14" => array("Opening","Kano","Fire often symbolizes intense emotions and passion. However, you are reminded that passion, like everything else, has two sides. Excessive passion could lead to destructive obsession, but on its positive side it can lead to creativity. A clarity of intent in your attitude is required in order to avoid falling into its negative side.\nIn the area of relationships, Kano announces a mutual opening. The torch of understanding is lit again for both, and the creative power of such fire could lead to great breakthroughs.","runes/14opening.jpg"),
	"15" => array("Warrior","Teiwaz","Masculine energy and the active principle are characteristic of this Rune, bringing as a result an anxiety to conquer. Teiwaz is the Rune of courage, dedication and absolute trust in ones own resources.\nIn situations on interpersonal relations or devotion to a cause, Teiwaz advises perseverance, at the same time reminding you that patience can sometimes be a kind of perseverance.\nLook within yourself and deeply analize the foundations of your life. By doing this, you may get to know and harness your deepest and most powerful resources.","runes/15warrior.jpg"),
	"16" => array("Growth","Berkana","This Rune indicates flowering and maturation, and is related to new forms. Growth can occur in everyday, family or interpersonal situations. The process of self-change is in movement and will be benefited.\nFor growth to occur freely, however, Berkana advises you to eliminate all resistances through a deep cleansing process. If necessary, ask for expert help to carry it out. Once resistance is cleared out through constancy and a proper attitude, then flowering can occur.","runes/16growth.jpg"),
	"17" => array("Movement","Ehwaz","This Rune signals a time of transition and transformation. It indicates changes of all kinds: of house, attitude, life, business directions or personal relations. Ehwaz informs you that you are required to face any necessary transition and to carry it out diligently.\nThere is a sense of continuous progress, a notion of growth that could well be related to a business venture or the development of an idea or project. There is much movement at hand. Now is the time to allow the old to die in order to make room for the new.","runes/17movement.jpg"),
	"18" => array("Flow","Laguz","The characteristics of this Rune are water, intuition and the ebb and flow of emotions, relations and vocations. Particularly, it announces the satisfaction of emotional needs.\nIn spite of the fact that everything flows appropriately at this moment, it often signals the need to cleanse, revalue, reorganize, recenter. It indicates that the intuitive aspect of your nature is awake, and therefore Laguz advises you to harness it.","runes/18flow.jpg"),
	"19" => array("Disruption","Hagalz","Maybe you find yourself surrounded by negative events apparently beyond your control. Drawing this Rune indicates the possibility of havoc or jolts in your reality, security, work, relations or beliefs.\nIt is necessary to realize that you are not at the mercy of external circumstances. I create my own reality. In other words, your own nature is creating what is happening, and therefore you are not helpless. Carefully examine the situations surrounding you and your own beliefs and attitudes towards them. Hagalaz informs you that you hold the solutions in your own hands.","runes/19disruption.jpg"),
	"20" => array("Journey","Raido","This Rune is related to communication and harmony of something made up of two elements. It often signals the possibility of a journey, be it in the physical world or to the depths of your being. Such journey could well be towards self-healing or self-change. Raido advises you to moderate any excess in your life.Maybe an unexpected union will occur in your life, or maybe you will reunite with someone close that you havent seen in a long time. Or maybe the reunion predicted by Raido refers to certain internal aspects in you that have been in conflict for some time.","runes/20journey.jpg"),
	"21" => array("Gateway","Thurisa","Thurisaz indicates the presence of new options opening before you. However, it is advised to stop in front of the gate before crossing it, to look at the road that led you up to here.\nThis Rune points toward the need of not acting yet, but to examine past experiences and circumstances before continuing towards success. It is not a moment to make decisions, but rather to strengthen your ability to wait. Review your past closely. Observe it, bless it, and let go of everything you need to let go of. Then cross the door.","runes/21gateway.jpg"),
	"22" => array("Breakthrough","Dagaz","Dagaz denotes important breakthroughs in relation to whatever concerns you. The moment is right and therefore success is assured. This is the Rune of radical trust, even if circumstances require you to jump to the void with apparently empty hands.\nIt often introduces an important time of prosperity and great results. However, you are reminded to pay attention and not allow yourself to be carried away or to behave carelessly in your new situation. Humility and generosity are advised.","runes/22breakthrough.jpg"),
	"23" => array("Standstill","Isa","Positive achievements are not probable at this moment. Activities are frozen and maybe all your plans are halted. Nevertheless, do not despair: this is the moment of gestation that precedes birth.\nThis pause is probably due more to external circumstances rather than internal. However, try to find what internal aspects keep you in this position and let them go. Clean, discard, let go of the past. This will help accelerate the thawing process.\nRemember that the seed sleeps under the ground during winter. Trust your own process and wait for the signs of Spring.","runes/23standstill.jpg"),
	"24" => array("Wholeness","Sowelu","This is a Rune of great power that indicates a moment of profound regeneration, a search for totality. It signals the need to become aware of your essence in order to express it in a creative manner, thus increasing your vital force. It also points to the need of admitting something that you have long denied, something that has remained under the shadows: now it is time to bring it out unto the light.\nIt might be prudent to stay away from a pressing situation, remembering that withdrawing at the right time is a sign of force and not of weakness.","runes/24wholeness.jpg"),
	"25" => array("Unknowable","Odin","The Blank Rune means the unknowable and unseen are active in your life at this time. In the beginning there was nothing, and in the end, nothing remains. Control can not be used on that which does not yet exist. As with the Fool in the Tarot, you may have to leap over the precipice into the void. But do so empty-handed and with utter faith. What becons is the creative power of the unknown.","runes/25unknowable.jpg")
);

?>